// flow-typed signature: 2a80052746d070794fd9a8758d5cf7dc
// flow-typed version: <<STUB>>/fetch-ponyfill_v^4.1.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fetch-ponyfill'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "fetch-ponyfill" {
  declare module.exports: (
    ?{ Promise: Object, XMLHttpRequest: Object }
  ) => {
    fetch: typeof fetch,
    Request: Request,
    Response: Response,
    Headers: Headers
  };
}
