// flow-typed signature: dcf14893739781b130f8bf77492a46dc
// flow-typed version: <<STUB>>/module_vx.x.x/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'module'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "module" {
  declare class Module {
    id: string;
    exports: Object;
    parent: ?Module;
    filename: string;
    loaded: boolean;
    children: Array<Module>;
    paths: Array<string>;
    constructor(id: string, parent: ?Module): Module;

    require: (id: string) => any;

    static builtinModules: Array<string>;
    static globalPaths: Array<string>;

    static wrap(script: string): string;
    static wrapper: [string, string];

    static Module: Class<Module>;

    static _nodeModulePaths(from: string): Array<string>;
  }

  declare module.exports: Class<Module>;
}
